name: watchlist_flutter_firestore
description: "Watchlist de filmes em Flutter Web com TMDB e Cloud Firestore."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.15.0
  cloud_firestore: ^6.10.0
  http: ^1.6.0
  google_fonts: ^8.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
